-- ===================================================================
-- Chamber Recall - database schema, version 1
-- ===================================================================
-- This file is meant to be readable by a person, not only by a program.
-- If you are a developer taking this project over, read this file first;
-- it is the most complete statement of what the system actually stores.
--
-- Conventions used throughout:
--   * Every id is a TEXT uuid, generated by the application.
--   * Every timestamp is a TEXT ISO-8601 string in UTC, e.g.
--     '2026-03-14T09:12:44.001Z'. Dates that a human thinks of as a
--     calendar day (a visit date) are TEXT 'YYYY-MM-DD' in local time.
--   * Booleans are INTEGER 0 or 1.
--   * NOTHING IS EVER HARD DELETED. Tables that can be "removed" have a
--     deleted_at column, and a trigger below makes a real DELETE fail.
--   * Every clinical field records who entered it. Those columns are
--     NOT NULL on purpose. Attribution is never optional.
-- ===================================================================

PRAGMA foreign_keys = ON;

-- -------------------------------------------------------------------
-- app_meta: a few facts about this database file itself.
-- -------------------------------------------------------------------
-- data_mode is the guard that keeps synthetic test data and real
-- patient data from ever sharing a file. The seed script refuses to
-- touch a database whose data_mode is 'live'.
CREATE TABLE app_meta (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- -------------------------------------------------------------------
-- app_user: the people who use the software.
-- -------------------------------------------------------------------
-- NOT in the original written spec. Added because every other table
-- refers to "who entered this", and that reference needs somewhere to
-- point. See docs/DECISIONS.md, decision 4.
--
-- role is fixed to exactly the three roles in the spec. A doctor who
-- writes his own notes is one row with role 'doctor'; the setup wizard
-- (milestone 9) may add a second row with role 'clinical_assistant'.
CREATE TABLE app_user (
  id           TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  role         TEXT NOT NULL CHECK (role IN ('doctor', 'clinical_assistant', 'front_desk')),
  -- Login credentials are not used yet; they arrive with the setup
  -- wizard in milestone 9. Null means "this user cannot sign in yet".
  pin_salt     TEXT,
  pin_hash     TEXT,
  is_active    INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at   TEXT NOT NULL,
  deleted_at   TEXT
);

-- -------------------------------------------------------------------
-- chamber: a place where the doctor sees patients.
-- -------------------------------------------------------------------
CREATE TABLE chamber (
  id                     TEXT PRIMARY KEY,
  name                   TEXT NOT NULL,
  -- Per-chamber letterhead for printing. JSON so the print layout can
  -- grow without a schema change. Null until configured.
  letterhead_config_json TEXT,
  created_at             TEXT NOT NULL,
  deleted_at             TEXT
);

-- -------------------------------------------------------------------
-- patient
-- -------------------------------------------------------------------
-- Identity notes, because this is the highest-risk table in the system:
--   * phone is indexed but is NOT unique and NOT an identifier.
--     Families share handsets; elderly patients give a son's number.
--   * A patient may have a name in Bangla, in English, or both. At
--     least one is required.
--   * Age: a chamber patient often does not know a date of birth, so
--     approx_age_years is common. It is stored WITH the date it was
--     recorded, because "45" recorded three years ago does not mean 45
--     today. Never display an approximate age without ageing it forward
--     from approx_age_recorded_on.
--   * search_name_bn / search_name_en hold Unicode-normalised,
--     case-folded, whitespace-collapsed copies of the names. They exist
--     so that substring search is plain and predictable. There is no
--     phonetic matching anywhere in version 1.
--   * merged_into_patient_id is set by the manual merge tool
--     (milestone 4). A row with this set is a duplicate that has been
--     folded into another record. It is never deleted, so a merge can
--     always be inspected, explained, and reversed.
CREATE TABLE patient (
  id                     TEXT PRIMARY KEY,
  full_name_bn           TEXT,
  full_name_en           TEXT,
  search_name_bn         TEXT,
  search_name_en         TEXT,
  phone                  TEXT,
  dob                    TEXT,
  approx_age_years       INTEGER CHECK (approx_age_years IS NULL OR (approx_age_years >= 0 AND approx_age_years <= 130)),
  approx_age_recorded_on TEXT,
  sex                    TEXT CHECK (sex IS NULL OR sex IN ('male', 'female', 'other')),
  address_free_text      TEXT,
  created_at             TEXT NOT NULL,
  created_by             TEXT NOT NULL REFERENCES app_user(id),
  updated_at             TEXT NOT NULL,
  deleted_at             TEXT,
  merged_into_patient_id TEXT REFERENCES patient(id),
  CHECK (full_name_bn IS NOT NULL OR full_name_en IS NOT NULL),
  -- An approximate age is meaningless without the date it was taken.
  CHECK ((approx_age_years IS NULL) = (approx_age_recorded_on IS NULL))
);

CREATE INDEX idx_patient_phone          ON patient(phone);
CREATE INDEX idx_patient_search_name_bn ON patient(search_name_bn);
CREATE INDEX idx_patient_search_name_en ON patient(search_name_en);
CREATE INDEX idx_patient_merged_into    ON patient(merged_into_patient_id);

-- -------------------------------------------------------------------
-- visit: one attendance. This table IS the serial register.
-- -------------------------------------------------------------------
-- The UNIQUE constraint on (chamber, date, serial) is what makes the
-- register trustworthy: two patients can never hold the same serial in
-- the same chamber on the same day. Soft-deleted visits keep their
-- serial reserved, exactly as a crossed-out line in a paper register
-- does not free up that number.
CREATE TABLE visit (
  id         TEXT PRIMARY KEY,
  patient_id TEXT NOT NULL REFERENCES patient(id),
  chamber_id TEXT NOT NULL REFERENCES chamber(id),
  visit_date TEXT NOT NULL,
  serial_no  INTEGER NOT NULL,
  arrived_at TEXT NOT NULL,
  seen_at    TEXT,
  status     TEXT NOT NULL CHECK (status IN ('waiting', 'in_chamber', 'done', 'left')),
  created_at TEXT NOT NULL,
  created_by TEXT NOT NULL REFERENCES app_user(id),
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  UNIQUE (chamber_id, visit_date, serial_no)
);

CREATE INDEX idx_visit_patient ON visit(patient_id, visit_date DESC);
CREATE INDEX idx_visit_day     ON visit(chamber_id, visit_date, serial_no);

-- -------------------------------------------------------------------
-- intake: the short structured history taken at the front desk.
-- -------------------------------------------------------------------
-- An intake may be started and never finished. completed_at null means
-- the assistant stopped partway, which is an expected and acceptable
-- outcome, not an error.
CREATE TABLE intake (
  id                TEXT PRIMARY KEY,
  visit_id          TEXT NOT NULL UNIQUE REFERENCES visit(id),
  recorded_by       TEXT NOT NULL REFERENCES app_user(id),
  started_at        TEXT NOT NULL,
  completed_at      TEXT,
  was_skipped       INTEGER NOT NULL DEFAULT 0 CHECK (was_skipped IN (0, 1)),
  -- Whether a family member or attendant was answering alongside the
  -- patient. This changes how the doctor should read the answers.
  helper_present    INTEGER CHECK (helper_present IS NULL OR helper_present IN (0, 1)),
  consent_version   TEXT,
  consent_given_at  TEXT,
  -- Consent to anonymised research use is asked and recorded
  -- separately. It cannot be inferred from the clinical consent above,
  -- and it cannot be added retrospectively.
  research_consent_version  TEXT,
  research_consent_given_at TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  deleted_at        TEXT
);

-- -------------------------------------------------------------------
-- intake_answer: one row per question presented.
-- -------------------------------------------------------------------
-- A row exists even when the question was skipped, with was_skipped=1.
-- "Asked and skipped" and "never asked" are different facts and the
-- doctor's screen must be able to tell them apart.
CREATE TABLE intake_answer (
  id               TEXT PRIMARY KEY,
  intake_id        TEXT NOT NULL REFERENCES intake(id),
  question_key     TEXT NOT NULL,
  answer_value     TEXT,
  answer_free_text TEXT,
  was_skipped      INTEGER NOT NULL DEFAULT 0 CHECK (was_skipped IN (0, 1)),
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL,
  UNIQUE (intake_id, question_key)
);

-- -------------------------------------------------------------------
-- red_flag_event: a screening rule fired and someone was told.
-- -------------------------------------------------------------------
-- rule_version is stored, not just rule_id, so that an escalation made
-- months ago can be explained against the rule text as it stood that
-- day. acknowledged_by is the assistant who tapped through the
-- full-screen warning.
CREATE TABLE red_flag_event (
  id              TEXT PRIMARY KEY,
  intake_id       TEXT NOT NULL REFERENCES intake(id),
  rule_id         TEXT NOT NULL,
  rule_version    TEXT NOT NULL,
  fired_at        TEXT NOT NULL,
  acknowledged_by TEXT REFERENCES app_user(id),
  acknowledged_at TEXT
);

CREATE INDEX idx_red_flag_intake ON red_flag_event(intake_id);

-- -------------------------------------------------------------------
-- vitals
-- -------------------------------------------------------------------
-- EVERY measurement column is nullable. Partial vitals are the normal
-- case, not a degraded one: a chamber may take blood pressure and
-- nothing else. Do not add NOT NULL here.
CREATE TABLE vitals (
  id                 TEXT PRIMARY KEY,
  visit_id           TEXT NOT NULL REFERENCES visit(id),
  recorded_by        TEXT NOT NULL REFERENCES app_user(id),
  recorded_at        TEXT NOT NULL,
  systolic_bp        INTEGER,
  diastolic_bp       INTEGER,
  pulse              INTEGER,
  temperature_c      REAL,
  weight_kg          REAL,
  height_cm          REAL,
  random_blood_sugar REAL,
  spo2               INTEGER,
  notes              TEXT,
  created_at         TEXT NOT NULL,
  updated_at         TEXT NOT NULL,
  deleted_at         TEXT
);

CREATE INDEX idx_vitals_visit ON vitals(visit_id);

-- -------------------------------------------------------------------
-- encounter: what happened in the chamber.
-- -------------------------------------------------------------------
-- entered_by is whoever typed it, which may be a clinical assistant
-- documenting while the doctor speaks.
-- doctor_confirmed_by / doctor_confirmed_at are set only by a doctor.
-- Until they are set, this encounter is a draft: it is not a
-- clinician-confirmed record and the interface must not present it as
-- one.
CREATE TABLE encounter (
  id                   TEXT PRIMARY KEY,
  visit_id             TEXT NOT NULL UNIQUE REFERENCES visit(id),
  chief_complaint      TEXT,
  examination_notes    TEXT,
  -- Free text, typed by a clinician. The software never generates,
  -- suggests, autocompletes, ranks or infers anything in this column.
  working_diagnosis    TEXT,
  decision_notes       TEXT,
  follow_up_after_days INTEGER,
  entered_by           TEXT NOT NULL REFERENCES app_user(id),
  doctor_confirmed_by  TEXT REFERENCES app_user(id),
  doctor_confirmed_at  TEXT,
  created_at           TEXT NOT NULL,
  updated_at           TEXT NOT NULL,
  deleted_at           TEXT
);

CREATE INDEX idx_encounter_visit ON encounter(visit_id);

-- -------------------------------------------------------------------
-- medication: what the doctor wrote on the prescription.
-- -------------------------------------------------------------------
-- A record of the doctor's own decision. The software does no
-- interaction checking and no dose calculation on this table, ever.
CREATE TABLE medication (
  id            TEXT PRIMARY KEY,
  encounter_id  TEXT NOT NULL REFERENCES encounter(id),
  drug_name     TEXT NOT NULL,
  strength      TEXT,
  dose          TEXT,
  frequency     TEXT,
  duration_days INTEGER,
  instructions  TEXT,
  sort_order    INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL,
  deleted_at    TEXT
);

CREATE INDEX idx_medication_encounter ON medication(encounter_id);

-- -------------------------------------------------------------------
-- investigation: a test ordered, and its result if one came back.
-- -------------------------------------------------------------------
-- result_date IS NULL means "ordered, no result recorded yet". That
-- single condition drives the outstanding-investigations block on the
-- Recall Card, which is the thing paper folders lose most often.
CREATE TABLE investigation (
  id             TEXT PRIMARY KEY,
  encounter_id   TEXT NOT NULL REFERENCES encounter(id),
  test_name      TEXT NOT NULL,
  ordered_date   TEXT NOT NULL,
  result_summary TEXT,
  result_date    TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL,
  deleted_at     TEXT
);

CREATE INDEX idx_investigation_encounter   ON investigation(encounter_id);
CREATE INDEX idx_investigation_outstanding ON investigation(result_date) WHERE result_date IS NULL;

-- -------------------------------------------------------------------
-- attachment: photographs of paper. How years of existing history get in.
-- -------------------------------------------------------------------
-- file_path is relative to the attachments folder beside the database,
-- so that moving the whole data folder to another laptop does not
-- break every link.
CREATE TABLE attachment (
  id           TEXT PRIMARY KEY,
  patient_id   TEXT NOT NULL REFERENCES patient(id),
  encounter_id TEXT REFERENCES encounter(id),
  file_path    TEXT NOT NULL,
  kind         TEXT NOT NULL CHECK (kind IN ('report', 'prescription_scan', 'old_paper_file', 'image')),
  captured_at  TEXT NOT NULL,
  caption      TEXT,
  created_at   TEXT NOT NULL,
  created_by   TEXT NOT NULL REFERENCES app_user(id),
  deleted_at   TEXT
);

CREATE INDEX idx_attachment_patient ON attachment(patient_id);

-- -------------------------------------------------------------------
-- audit_log: append-only. Enforced by the database, not by politeness.
-- -------------------------------------------------------------------
-- The triggers below make UPDATE and DELETE on this table fail at the
-- database level. There is deliberately no code path anywhere in the
-- application that can edit or remove an audit row, and adding one
-- would not work even if someone tried.
--
-- details_json is not in the original written spec. It was added
-- because reconstructing a patient merge months later is impossible
-- without knowing which records were involved. See docs/DECISIONS.md,
-- decision 5.
CREATE TABLE audit_log (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  actor_role   TEXT NOT NULL CHECK (actor_role IN ('doctor', 'clinical_assistant', 'front_desk', 'system')),
  actor_id     TEXT,
  action       TEXT NOT NULL,
  entity       TEXT NOT NULL,
  entity_id    TEXT,
  details_json TEXT,
  timestamp    TEXT NOT NULL
);

CREATE INDEX idx_audit_entity ON audit_log(entity, entity_id);
CREATE INDEX idx_audit_time   ON audit_log(timestamp);

CREATE TRIGGER audit_log_is_append_only_no_update
BEFORE UPDATE ON audit_log
BEGIN
  SELECT RAISE(ABORT, 'audit_log is append-only: rows can never be changed');
END;

CREATE TRIGGER audit_log_is_append_only_no_delete
BEFORE DELETE ON audit_log
BEGIN
  SELECT RAISE(ABORT, 'audit_log is append-only: rows can never be deleted');
END;

-- -------------------------------------------------------------------
-- usage_event: how the software is actually being used.
-- -------------------------------------------------------------------
-- This feeds the pilot report. It records timings and actions, never
-- clinical content.
CREATE TABLE usage_event (
  id          TEXT PRIMARY KEY,
  event_type  TEXT NOT NULL,
  actor_id    TEXT REFERENCES app_user(id),
  visit_id    TEXT REFERENCES visit(id),
  timestamp   TEXT NOT NULL,
  duration_ms INTEGER
);

CREATE INDEX idx_usage_type_time ON usage_event(event_type, timestamp);
CREATE INDEX idx_usage_actor     ON usage_event(actor_id, timestamp);

-- -------------------------------------------------------------------
-- Nothing is ever hard deleted.
-- -------------------------------------------------------------------
-- Each of these triggers turns a real DELETE into an error. To remove
-- something from view, set its deleted_at. This is a safety net against
-- a future mistake, including one of mine.
CREATE TRIGGER patient_no_hard_delete       BEFORE DELETE ON patient       BEGIN SELECT RAISE(ABORT, 'patient rows are never deleted: set deleted_at instead'); END;
CREATE TRIGGER visit_no_hard_delete         BEFORE DELETE ON visit         BEGIN SELECT RAISE(ABORT, 'visit rows are never deleted: set deleted_at instead'); END;
CREATE TRIGGER intake_no_hard_delete        BEFORE DELETE ON intake        BEGIN SELECT RAISE(ABORT, 'intake rows are never deleted: set deleted_at instead'); END;
CREATE TRIGGER intake_answer_no_hard_delete BEFORE DELETE ON intake_answer BEGIN SELECT RAISE(ABORT, 'intake_answer rows are never deleted'); END;
CREATE TRIGGER red_flag_no_hard_delete      BEFORE DELETE ON red_flag_event BEGIN SELECT RAISE(ABORT, 'red_flag_event rows are never deleted'); END;
CREATE TRIGGER vitals_no_hard_delete        BEFORE DELETE ON vitals        BEGIN SELECT RAISE(ABORT, 'vitals rows are never deleted: set deleted_at instead'); END;
CREATE TRIGGER encounter_no_hard_delete     BEFORE DELETE ON encounter     BEGIN SELECT RAISE(ABORT, 'encounter rows are never deleted: set deleted_at instead'); END;
CREATE TRIGGER medication_no_hard_delete    BEFORE DELETE ON medication    BEGIN SELECT RAISE(ABORT, 'medication rows are never deleted: set deleted_at instead'); END;
CREATE TRIGGER investigation_no_hard_delete BEFORE DELETE ON investigation BEGIN SELECT RAISE(ABORT, 'investigation rows are never deleted: set deleted_at instead'); END;
CREATE TRIGGER attachment_no_hard_delete    BEFORE DELETE ON attachment    BEGIN SELECT RAISE(ABORT, 'attachment rows are never deleted: set deleted_at instead'); END;
CREATE TRIGGER app_user_no_hard_delete      BEFORE DELETE ON app_user      BEGIN SELECT RAISE(ABORT, 'app_user rows are never deleted: set deleted_at instead'); END;
CREATE TRIGGER chamber_no_hard_delete       BEFORE DELETE ON chamber       BEGIN SELECT RAISE(ABORT, 'chamber rows are never deleted: set deleted_at instead'); END;

-- A red flag event, once fired, is a permanent record of a clinical
-- escalation. Only the acknowledgement columns may ever be filled in.
CREATE TRIGGER red_flag_only_acknowledgement_may_change
BEFORE UPDATE ON red_flag_event
WHEN OLD.intake_id    IS NOT NEW.intake_id
  OR OLD.rule_id      IS NOT NEW.rule_id
  OR OLD.rule_version IS NOT NEW.rule_version
  OR OLD.fired_at     IS NOT NEW.fired_at
BEGIN
  SELECT RAISE(ABORT, 'a fired red flag can never be altered; only its acknowledgement may be recorded');
END;
